[package]
name = "rust-algorithms"
version = "0.1.0"
authors = ["Alok Puranik <alokpuranik1@gmail.com>"]
edition = "2018"

[[bin]]
name = "alg-example"
path = "src/bin.rs"

[dependencies]

num = "0.2.0"
